### PR TITLE
fix: history entries cursor + HistoryController test

### PR DESCRIPTION
**Pull request by testrocket**
PR fixes history navigation by reseting history cursor & history entries by removing oldest and NOT latest entries.

### CODE REVIEW

**Review by mlech-reef — APPROVED** [review]

**Comment by ppolewicz** [comment]
@testrocket can this be submitted upstream to the main `local-echo` repository to fix the bug there as well?

**Comment by testrocket** [comment]
@ppolewicz I think so. However not sure about one thing: I made changes only in src folder but not dist. To answer you question: it solves 2 bugs but  updates for files in dist folder are missing here...
@mlech-reef should we update files in dist folder as well?

**Comment by mlech-reef** [comment]
@testrocket I don't know.

Please keep in mind it's not our first change in this repository. I think I did one or two and Manoj. I'm not sure if they could be submitted to the upstream or they are a kind of workarounds that only make sense for reef.pl site like this thing with `cat` (https://github.com/reef-technologies/bash-emulator/pull/4)

**Comment by ppolewicz** [comment]
I've looked at the blame of the vincinity of #1 patch and it looks like it's far away from our other changes. @testrocket would you like to submit #1 to upstream? Ideally that would make an upgrade of our `local-echo` easier in the future, maybe we'd get new features and bug fixes this way without doing everything by ourselves.

**Comment by testrocket** [comment]
Well we can do it however I'm not sure how this supposed to work right now. I'm mean should create another (same) PR and submit it again?
Also there seems to be PR in original repo for one of our issues but it hasn't been reviewed for a while...

**Comment by ppolewicz** [comment]
can't find it. Link?

**Pull request merged**
